# Generated by Django 4.0.6 on 2022-07-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorDesc',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
