# Generated by Django 4.0.6 on 2022-07-13 16:58

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_authordesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cont',
            field=froala_editor.fields.FroalaField(default=1),
            preserve_default=False,
        ),
    ]
