# Generated by Django 4.0.6 on 2022-07-13 17:36

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_cont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cont',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
